$c->{search}->{advanced} = 
{
	search_fields => [
	#	{ meta_fields => [ "documents" ] },
	    { meta_fields => [ "title" ] },
	    { meta_fields => [ "alt_title" ] },
		{ meta_fields => [ "abstract" ] },
		{ meta_fields => [ "keywords" ] },
	#	{ meta_fields => [ "collection_date_date_from" ] },
	#	{ meta_fields => [ "collection_date_date_to" ] },
	#	{ meta_fields => [ "date_type" ] },
		{ meta_fields => [ "date" ] },
		{ meta_fields => [ "collection_mode_cm" ] },
		{ meta_fields => [ "collection_method" ] },
	#	{ meta_fields => [ "geographic_cover" ] },
		{ meta_fields => [ "language_l" ] },
		{ meta_fields => [ "note" ] },
		
		{ meta_fields => [ "creators_name" ] },
		{ meta_fields => [ "contributors_name" ] },
	#	{ meta_fields => [ "contact_email" ] },
	#	{ meta_fields => [ "repo_link_title" ] },
	#	{ meta_fields => [ "repo_link_link" ] },
	#	{ meta_fields => [ "related_resources_title" ] },
	#	{ meta_fields => [ "related_resources_url" ] },
	#	{ meta_fields => [ "related_resources_type" ] },
		{ meta_fields => [ "projects" ] },
		{ meta_fields => [ "grant" ] },
		{ meta_fields => [ "funders" ] },
		{ meta_fields => [ "corp_creators" ] },
		{ meta_fields => [ "divisions" ] },
		{ meta_fields => [ "research_centre" ] },
		{ meta_fields => [ "research_groups" ] },
		{ meta_fields => [ "copyright_holders" ] },
		{ meta_fields => [ "publisher" ] },
		{ meta_fields => [ "place_of_pub" ] },

	#	{ meta_fields => [ "department" ] },
	#	{ meta_fields => [ "editors_name" ] },
	#	{ meta_fields => [ "ispublished" ] },
	#	{ meta_fields => [ "refereed" ] },
	#	{ meta_fields => [ "publication" ] },
	#	{ meta_fields => [ "documents.format" ] },
	],
	preamble_phrase => "cgi/advsearch:preamble",
	title_phrase => "cgi/advsearch:adv_search",
	citation => "result",
	page_size => 20,
	order_methods => {
		"byyear" 	 => "-date/creators_name/title",
		"byyearoldest"	 => "date/creators_name/title",
		"bynameror"  	 => "creators_name/-date/title",
		"bytitle" 	 => "title/creators_name/-date"
	},
	default_order => "byyear",
	show_zero_results => 1,
};

